### ISSUE TITLE
login fails:  with  LedgerError - ResourceNotFound: ledger:

### ISSUE THREAD

**Issue by KennethNagin** [IBM-Blockchain/fabric-boilerplate#11]
I deployed the boilerplate according to the instructions: "Running the application automatically" with the docker-compose to bring up the fabric.  I checked that the app is running by brouwsing http://localhost:8080/ in your browser. And attempted to login with the user credentials in testData/testData.json.  However the log in fails.

Here are the details:

The login fails  with  LedgerError - ResourceNotFound: ledger: resource not found)"}

Log from the app:
(node:13033) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): [object Object]
debug: Login attempt w/ username:  john1
error: [SDK] error on query: {"error":{"status":"FAILURE","msg":{"type":"Buffer","data":[69,114,114,111,114,58,70,97,105,108,101,100,32,116,111,32,108,97,117,110,99,104,32,99,104,97,105,110,99,111,100,101,32,115,112,101,99,40,67,111,117,108,100,32,110,111,116,32,103,101,116,32,100,101,112,108,111,121,109,101,110,116,32,116,114,97,110,115,97,99,116,105,111,110,32,102,111,114,32,56,56,56,49,50,98,48,51,98,97,55,100,55,53,48,50,51,53,99,56,57,50,97,56,97,57,57,57,50,54,102,56,50,49,56,53,54,53,97,98,56,100,98,55,99,98,52,52,57,55,56,49,97,100,99,49,55,57,56,97,49,54,55,100,32,45,32,76,101,100,103,101,114,69,114,114,111,114,32,45,32,82,101,115,111,117,114,99,101,78,111,116,70,111,117,110,100,58,32,108,101,100,103,101,114,58,32,114,101,115,111,117,114,99,101,32,110,111,116,32,102,111,117,110,100,41]}},"msg":"Error:Failed to launch chaincode spec(Could not get deployment transaction for 88812b03ba7d750235c892a8a99926f8218565ab8db7cb449781adc1798a167d - LedgerError - ResourceNotFound: ledger: resource not found)"}
error:  
{ error: 
   { status: 'FAILURE',
     msg: 
      { '0': 69,
lots of number follow
      }
        '204': 41 } },
  msg: 'Error:Failed to launch chaincode spec(Could not get deployment transaction for 88812b03ba7d750235c892a8a99926f8218565ab8db7cb449781adc1798a167d - LedgerError - ResourceNotFound: ledger: resource not found)' }
(node:13033) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): [object Object]

log from the fabric:
vp0_1        | 2016/12/06 12:39:48 transport: http2Server.HandleStreams failed to receive the preface from client: EOF

I also took a look at ./logs/logs.log
nagin@rcc-hrl-kvg-558:~/work/src/github.com/KennethNagin/fabric-boilerplate$ cat logs/logs.log
{"level":"error","message":"[SDK] error on query: {\"error\":{\"status\":\"FAILURE\",\"msg\":{\"type\":\"Buffer\",\"data\":[69,114,114,111,114,58,70,97,105,108,101,100,32,116,111,32,108,97,117,110,99,104,32,99,104,97,105,110,99,111,100,101,32,115,112,101,99,40,67,111,117,108,100,32,110,111,116,32,103,101,116,32,100,101,112,108,111,121,109,101,110,116,32,116,114,97,110,115,97,99,116,105,111,110,32,102,111,114,32,56,56,56,49,50,98,48,51,98,97,55,100,55,53,48,50,51,53,99,56,57,50,97,56,97,57,57,57,50,54,102,56,50,49,56,53,54,53,97,98,56,100,98,55,99,98,52,52,57,55,56,49,97,100,99,49,55,57,56,97,49,54,55,100,32,45,32,76,101,100,103,101,114,69,114,114,111,114,32,45,32,82,101,115,111,117,114,99,101,78,111,116,70,111,117,110,100,58,32,108,101,100,103,101,114,58,32,114,101,115,111,117,114,99,101,32,110,111,116,32,102,111,117,110,100,41]}},\"msg\":\"Error:Failed to launch chaincode spec(Could not get deployment transaction for 88812b03ba7d750235c892a8a99926f8218565ab8db7cb449781adc1798a167d - LedgerError - ResourceNotFound: ledger: resource not found)\"}","timestamp":"2016-12-06T09:55:27.820Z"}
....

--Ken

**Comment by czar0** [comment]
Hi @KennethNagin , sorry for the late answer.
That error shows your chaincode has not been built correctly. I may be related to the fact you do not have all the (or any) vendor dependencies, that is the installation of `govend` package failed somehow.
I have updated the README with some troubleshooting (including this case). Please have a look and get back here to give us updates.

**Comment by KennethNagin** [comment]
There is definitely an improvement!
The login prints out:
Jane
12345678 - Lorem Ipsum
87654321 - Ipsum Lorem
Footer
With a grey button titled "Log Out"
Is this what is expected?

The log from the fabric looks like this:
 debug: Login attempt w/ username:  jane1
info: [SDK] completed query: "{ \"authenticated\": true, \"user\": {\"userId\":\"jane1\",\"salt\":\"b754e470be74c18bd6927a9cfffcc212\",\"hash\":\"218fe81170699a59cdf11cb75df4b55a4f25acf701d1e65c9d62158fe07582c3711992cbedec335b5e174c291065172b035cff1c6f9249ab7f9406043cb00b88\",\"firstName\":\"Jane\",\"lastName\":\"Doe\",\"things\":[\"87654321\"],\"address\":\"128 West 44th Street, New York, NY 10036, United States\",\"phoneNumber\":\"0900 0024\",\"emailAddress\":\"janedoe@gmail.com\"}  }"
debug: verifying API call
debug: Token approved
-- Query all things --
info: [SDK] completed query: "[{\"id\":\"12345678\",\"description\":\"Lorem Ipsum\"},{\"id\":\"87654321\",\"description\":\"Ipsum Lorem\"}]"
Retrieved things from the blockchain: # 2

However on the initial bring up.  The messages from the node app/blockcode is:
vp0_1        | 2016/12/11 10:46:31 transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 172.17.0.3:7051->172.17.0.1:52269: read: connection reset by peer
vp0_1        | 2016/12/11 10:46:32 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write tcp 172.17.0.3:7051->172.17.0.1:52271: write: connection reset by peer"

When restart with the start.sh script I do not see the above failed messages.

Should I be concerned about the failed messages?

--Ken

**Comment by czar0** [comment]
@KennethNagin Yes, that is how it should work. Does your peer keep logging after those messages? Is the application still working? In positive answer, I would not worry too much about those, they are apparently some debug messages from gRPC module.

**Comment by KennethNagin** [comment]
Great.  I will now see whether this will also work on bluemix.
