### ISSUE TITLE
npm run deploy-bluemix fails

### ISSUE THREAD

**Issue by KennethNagin** [IBM-Blockchain/fabric-boilerplate#14]
After successfully launching the boilerplate locally I attempting deploying the blockcode on bluemix.
First I launched a new blockchain service on bluemix.  I copied its credential's to the credential.json and updated the manifest.yml. I then ran "npm run deploy-bluemix" but it failed:

error: Error registering and enrolling user john1
error:  Error: proto: can't skip unknown wire type 7 for protos.Attribute
    at /home/nagin/work/src/github.com/fabric-boilerplate/node_modules/grpc/src/node/src/client.js:411:17
error: Error registering and enrolling user jane1
error:  Error: proto: can't skip unknown wire type 7 for protos.Attribute
    at /home/nagin/work/src/github.com/fabric-boilerplate/node_modules/grpc/src/node/src/client.js:411:17
error: uncaughtException: ENOENT: no such file or directory, open 'logs/logs.log' 
{ date: 'Sun Dec 11 2016 16:00:29 GMT+0200 (IST)',
  process: 
   { pid: 15347,
     uid: 1001,
     gid: 1001,
     cwd: '/home/nagin/work/src/github.com/fabric-boilerplate/blockchain/deployBluemix',
     execPath: '/usr/local/bin/node',
     version: 'v6.9.2',
     argv: 
      [ '/usr/local/bin/node',
        '/home/nagin/work/src/github.com/fabric-boilerplate/blockchain/deployBluemix/deployAndRegister.js' ],
     memoryUsage: { rss: 138272768, heapTotal: 88236032, heapUsed: 63126288 } },
  os: 
   { loadavg: [ 1.0830078125, 1.052734375, 1.05078125 ],
     uptime: 14656718 },
  trace: 
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true } ],
  stack: 
   [ 'Error: ENOENT: no such file or directory, open \'logs/logs.log\'',
     '    at Error (native)' ] }
info: Deploy results: {"uuid":"54daf459f017d20fc7462163295c5efde3f16e8d1e209150adca084468b455e3","chaincodeID":"54daf459f017d20fc7462163295c5efde3f16e8d1e209150adca084468b455e3","result":"TODO: get actual results; waited 20 seconds and assumed deploy was successful"}
info: Saving latest chaincodeID to file

Few a very short time the blockchain was deployed but stopped.  But then it disappeared.

**Comment by czar0** [comment]
@KennethNagin That should be related to missing certificate (or wrong path). I had a similar one before. Moreover, I think that procedure of deploying is deprecated. In few days a new update should be available on _master_ with some great new features (included a simplified process to deploy on Bluemix and fabric v0.6.1 running). If you want to try it already, you can checkout branch **ng1** (it may be unstable).

**Comment by czar0** [comment]
Fixed in #13
