### ISSUE TITLE
Prerequisites section in README.md is wrong

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/fabric-boilerplate#15]
I helped someone get going in the Hyperledger Slack channels with this sample, I think the docs need a couple of changes.

The PATH is wrong for installed Go executables (the `src` directory should not be there):
`export PATH=$PATH:$GOPATH/src/bin`
... _should be_ ...
`export PATH=$PATH:$GOPATH/bin`

The `go get -u github.com/govend/govend` command was missed.
It might be worth calling more attention to it by wrapping it in backticks?

**Comment by czar0** [comment]
@sstone1 Thanks for pointing out those findings.
I just merged #16 into master which is correcting the wrong bin path.
The command to download `govend` was already there, in _Prerequisites_ section.
