### ISSUE TITLE
Add GRPC to packages

### ISSUE THREAD

**Issue by ghost** [IBM-Blockchain/fabric-boilerplate#2]
I had to add "grpc": "0.13.0" to the dependencies in packages.json for it to work out of the box

**Comment by rmoedt** [comment]
Was that needed to run it locally or for deploying to bluemix?
What does your environment look like?

**Comment by czar0** [comment]
@pdulong "grpc" is a dependency of "hfc" (client sdk) package, as reported [here](https://www.npmjs.com/package/hfc), so it should be included already in your environment. How did you notice its missing? Can you please post a log from your terminal after a fresh "npm install"?
