### ISSUE TITLE
Erro on Auto Redeployment 

### ISSUE THREAD

**Issue by gokulamurthy** [IBM-Blockchain/fabric-boilerplate#24]
Please find below logs when it runs for auto redeployment after some changes on chaincode file.

debug: [SDK] Chaincode changed. Redeploying...
debug: [SDK] Checking if redeploy is needed
debug: Found chaincode id from file: dd9a29745edac15a8f9670ced54df58e9fa7cc402e1987a960cd9f33125f5331
debug: [SDK] Going to deploy chaincode
debug: [SDK] Chaincode changed. Redeploying...
debug: [SDK] Checking if redeploy is needed
debug: Found chaincode id from file: dd9a29745edac15a8f9670ced54df58e9fa7cc402e1987a960cd9f33125f5331
debug: [SDK] Going to deploy chaincode
error: [SDK] Failed to deploy chaincode
error: [SDK] Deploy error:
{ error: {},
  msg: 'Error: Error reading deployment archive [/tmp/deployment-package.tar.gz]: Error: ENOENT: no such file or directory, open \'/tmp/deployment-package.tar.gz\'' }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)

@czar0  Please help me here too!

**Comment by arner** [comment]
Closed as this should be resolved in the new version.
