### ISSUE TITLE
npm run installgo is leading to nowhere

### ISSUE THREAD

**Issue by raj040492** [IBM-Blockchain/fabric-boilerplate#28]
First I tried npm start and got this error 

Error:Failed to launch chaincode spec(Could not get deployment transaction for a6d7d80d48346954df4e9143b346f3c4b27d3129b1ba28ec295c11138efc9c7a - LedgerError - ResourceNotFound: ledger: resource not found)

Since it was refered in README.md I followed the steps and tried "npm run installgo" which lead to further errors 

Failed at the server@0.0.0 installgo script 'cd src/build-chaincode && GOPATH=$(pwd)/../.. && govend -v'.

I understand the above line originates from package.json. But I dont know how to proceed further.

node version: 6.9.2; npm version 4.0.5

Any tips?

**Comment by raj040492** [comment]
My team mate with OSX was able to go over this step in a jiffy?

So, is it possible that this is a linux specific issue. Please enlighten on this aspect as well

**Comment by czar0** [comment]
@raj040492 It is clear your chaincode is not deployed, I guess because you miss the `vendors`dependencies. Is `govend` correctly installed and it is in your `$PATH`? Please strictly follow the _Prerequisites_ section in the README and paste here below complete logs.

**Comment by raj040492** [comment]
I too realised the same.. Removed govend completely and reinstalled the same.. edited PATH variables and ensured govend is in the path variable ; Followed all prerequisites to the core.

but still the same error.

npm ERR! Linux 3.13.0-101-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "nodemon"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.0 nodemon: `GOPATH=$(pwd) nodemon ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.0.0 nodemon script 'GOPATH=$(pwd) nodemon ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     GOPATH=$(pwd) nodemon ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

**Comment by czar0** [comment]
@raj040492 Have you installed `nodemon` globally as written in the README?
```
npm install nodemon -g
```

**Comment by pytpriscila** [comment]
I have the same problem...I already installed the nodemon. If I run only nodemon woks correctly, but when I run the ./start the error happens

**Comment by arner** [comment]
Closed as the new version should resolve this issue.
