### ISSUE TITLE
Trying to understand authentication

### ISSUE THREAD

**Issue by marcusvcs** [IBM-Blockchain/fabric-boilerplate#29]
Hi,

I tested the code locally and everything seems to work fine, but I have trouble to understanding how the example authenticate the users.
My background is Ethereum, there when you invoke a function you have to sign the transaction.
It seems to me that the check for password happens only on web server side, so I did not see how, when you call a function in the blockchain, you make sure that you are really the user that you say you are.
Is it because I am testing locally?
Is there any documentation that can help me understand this?

Thanks.

**Comment by arner** [comment]
Hi Marcus,

With Fabric all transactions are also signed by the end user. In our application we add another layer (compared to a Dapp that could run in the Myst browser for instance): the server. The server is doing transactions on behalf of the user. To be able to do this, the server keeps the private keys of all the users that registered. So we assume trust between the user and the server he uses to login. Technically we would be perfectly able to create a client application that uses the HFC to connect directly to the network, but that is not the way we implemented this simple example. 

Regards, Arne

**Comment by marcusvcs** [comment]
Hi Arne, I understood now, thank you.
