### ISSUE TITLE
Suggestion - ui-router instead of ngRouter

### ISSUE THREAD

**Issue by ruslan-ardashev** [IBM-Blockchain/fabric-boilerplate#31]
* ui-router allows for nested views and multiple named views. This is very useful with larger app where you may have pages that inherit from other sections.
* ui-router allows for you to have strong-type linking between states based on state names. Change the url in one place will update every link to that state when you build your links with ui-sref. Very useful for larger projects where URLs might change.
* There is also the concept of the decorator which could be used to allow your routes to be dynamically created based on the URL that is trying to be accessed. This could mean that you will not need to specify all of your routes before hand.
* states allow you to map and access different information about different states and you can easily pass information between states via $stateParams.
* You can easily determine if you are in a state or parent of a state to adjust UI element (highlighting the navigation of the current state) within your templates via $state provided by ui-router which you can expose via setting it in $rootScope on run.

--> more powerful client demos --> more IBM blockchain users : )

http://stackoverflow.com/questions/21023763/angularjs-difference-between-angular-route-and-angular-ui-router

**Comment by arner** [comment]
Thanks for the suggestion, would definitely be an improvement. Feel free to make a pull request!

Speaking of more powerful client demos, check out our v2-typescript branch. It's a great improvement from the current version and includes a TypeScript NodeJS server, Angular 2 on the frontend, and the only needed dependencies are docker + docker-compose.

**Comment by arner** [comment]
Closed since we don't support the JS version anymore.
