### ISSUE TITLE
Feature Suggestion - Automatic New Tab + Docker Attach

### ISSUE THREAD

**Issue by ruslan-ardashev** [IBM-Blockchain/fabric-boilerplate#34]
Team,
Thank you for this awesome boilerplate, it's really expedited the development process on my end!
If you don't mind I would love to suggest a feature for at some point in the future - a script that opens a new tab, continuously runs ```docker ps```, and when the chaincode ID appears, runs ```docker attach ####``` for easy debugging!

Would love to even collaborate on developing this as part of ```start.sh``` once I wrap up my current project.

**Comment by arner** [comment]
We don't need a start script anymore now we spin up the whole application with docker-compose. Existing tools like Kitematic can perform the suggested functionality.
