### ISSUE TITLE
Requires hyperledger/fabric:latest image

### ISSUE THREAD

**Issue by jonathan-yk-tan** [IBM-Blockchain/fabric-boilerplate#4]
Peer nodes use the image "hyperledger/fabric:latest" for spawning chaincode containers. Had to tag the most stable image I have "yeasy/hyperledger:0.5-dp" to "hyperledger/fabric:latest" inorder for chaincode to be deployed successfully.

**Comment by thejdavid** [comment]
same here

**Comment by czar0** [comment]
Correct. You can find all the needed images here: [fabric-boilerplate docker hub](https://hub.docker.com/u/rikmoedt/).
I will update the readme soon. Thanks to notice!

**Comment by czar0** [comment]
You missed this in the README:

> ### Setting up Hyperledger
> 1. go to `fabric-boilerplate/src/chaincode/vendor/github.com/hyperledger`
> 2. get the hyperledger code `git clone https://github.com/hyperledger-archives/fabric.git`
> 3. go into the fabric folder `cd fabric`
> 4. Switch to a seprate branch `git checkout v0.5-developer-preview`
> 5. run `bash scripts/provision/docker.sh 0.0.10`
> 
> This will prepare a docker baseimage in which the chaincode will be launched and deployed. This process takes quite a while.

Even though, you do not need anymore to launch that script and generate the fabric-baseimage, as we uploaded the same version in our docker hub.
I will add some instructions to pull and tag correctly all the images.
