### ISSUE TITLE
Use IBM's docker-compose & images?

### ISSUE THREAD

**Issue by mrshah-at-work** [IBM-Blockchain/fabric-boilerplate#6]
This is a suggestion:
Should we use IBM's docker-compose and images over here?
https://hub.docker.com/r/ibmblockchain/fabric-peer/

**Comment by mastersingh24** [comment]
@mrshah-at-ibm  - at this point it would make sense to update this to the v0.6 images and eventually to the upcoming BMX version.  So I agree

**Comment by czar0** [comment]
Hi all, we are now using official docker images from [Hyperledger Docker Hub](https://hub.docker.com/r/hyperledger/).
