### ISSUE TITLE
NPM install - gyp ERR! build error gyp ERR! stack error

### ISSUE THREAD

**Issue by d-chau** [IBM-Blockchain/fabric-boilerplate#9]
Running npm -version 3.10.8 and node -v 6.9.1.

Unable to complete npm install command. 

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\....\fabric_boil
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:....\\workspace\\block-to-build" "--module=C:\\....\\fabric_boilerplate\\fabricmodule_path=C:\....n\\fabric_boilerplate\\fabric-boilerpla
gyp ERR! cwd C...fabric_boilerplate\fabric-boilerplate\nod
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:...nodejs\node.exe C:\U...\ld --fallback-to-build --module=C:\....\fabric_boilerplate\fabpath=C:\....\blockchain\fabric_boilerplate\fabric-boilerplate\node_module
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (...\blockcha29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\...\\nodejs\\node.exe" "C:...\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:..fabric_boilerplate\fabric-boiler
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute ...\fabric_boilerplate\fabric-boilerplate\node_modules\gr\...\fabric_boilerplate\fabric-boilerplate\node_modules\grpc\src\node\extension_binar
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\...nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.13.2-pre1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.13.2-pre1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:/
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\...\fabric_boilerplate\fabric-boilerplate\npm

**Comment by czar0** [comment]
#7

**Comment by czar0** [comment]
Hey @d-chau , I think this is similar to #7.

**Comment by d-chau** [comment]
@czar0 Thank you. Fix is below.
https://github.com/IBM-Blockchain/fabric-boilerplate/issues/7
